version: '2'

services:
  drone-server:
    image: drone/drone:0.8.6
    ports:
      - 8000:8000
      - 9000:9000
    volumes:
      - ./drone-data:/var/lib/drone/
    env_file:
      - ./drone.env
    restart: always
    environment:
      - DRONE_OPEN=false
      - DRONE_HOST=http://localhost:8000
      - DRONE_GITHUB=true
      # Variables below set via drone.env file
      - DRONE_GITHUB_CLIENT=0c9f2a57663b7b8716d3
      - DRONE_GITHUB_SECRET=767b9c924ea81edd1d894ed775430d83631c8658
      - DRONE_SECRET=eopanasiuk

  drone-agent:
    image: drone/agent:0.8.6
    command: agent
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./drone.env
    environment:
      - DRONE_SERVER=drone-server:9000
      # Variables below set via drone.env file
      - DRONE_SECRET=eopanasiuk
